package apps

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/aduthekaddu/relay/internal/config"
)

// deskApp is one entry of the desktop launcher catalog.
type deskApp struct {
	ID   string
	Name string
	Icon string   // freedesktop icon name for the panel and menu
	Argv []string // resolved command; Argv[0] is absolute
}

// builtinDeskApps lists the catalog entries Relay knows about, each with
// candidate binaries tried in order.
var builtinDeskApps = []struct {
	id, name, icon string
	bins           []string
	args           func(dataDir string) []string
}{
	{id: "chrome", name: "Chrome", icon: "google-chrome",
		bins: []string{"google-chrome", "google-chrome-stable", "chromium", "chromium-browser"},
		args: func(dataDir string) []string {
			return []string{
				"--user-data-dir=" + filepath.Join(dataDir, "desktop", "chrome"),
				"--no-first-run", "--no-default-browser-check",
			}
		}},
	{id: "blender", name: "Blender", icon: "blender", bins: []string{"blender"}},
	{id: "terminal", name: "Terminal", icon: "utilities-terminal",
		bins: []string{"xterm", "x-terminal-emulator", "alacritty", "xfce4-terminal", "gnome-terminal", "konsole"}},
	{id: "files", name: "Files", icon: "system-file-manager",
		bins: []string{"thunar", "pcmanfm", "nautilus", "nemo", "caja", "dolphin"}},
}

// deskCatalog resolves the built-in apps that are installed, then the
// configured desktop.apps (which may override a built-in by id).
func deskCatalog(cfg []config.DesktopAppConfig, dataDir, home string, lookPath func(string) (string, error)) ([]deskApp, []error) {
	var out []deskApp
	index := map[string]int{}
	for _, b := range builtinDeskApps {
		for _, bin := range b.bins {
			p, err := lookPath(bin)
			if err != nil {
				continue
			}
			argv := []string{p}
			if b.args != nil {
				argv = append(argv, b.args(dataDir)...)
			}
			index[b.id] = len(out)
			out = append(out, deskApp{ID: b.id, Name: b.name, Icon: b.icon, Argv: argv})
			break
		}
	}
	var errs []error
	for _, c := range cfg {
		id := strings.ToLower(strings.TrimSpace(c.ID))
		if !appIDRe.MatchString(id) {
			errs = append(errs, fmt.Errorf("desktop app %q: invalid id", c.ID))
			continue
		}
		if len(c.Command) == 0 {
			errs = append(errs, fmt.Errorf("desktop app %q: no command", id))
			continue
		}
		argv := append([]string(nil), c.Command...)
		argv[0] = expandHome(argv[0], home)
		p, err := lookPath(argv[0])
		if err != nil {
			errs = append(errs, fmt.Errorf("desktop app %q: command not found: %s", id, c.Command[0]))
			continue
		}
		argv[0] = p
		a := deskApp{ID: id, Name: c.Name, Icon: c.Icon, Argv: argv}
		if a.Name == "" {
			a.Name = id
		}
		if a.Icon == "" {
			a.Icon = "application-x-executable"
		}
		if i, ok := index[id]; ok {
			out[i] = a
			continue
		}
		index[id] = len(out)
		out = append(out, a)
	}
	return out, errs
}

// shellQuote quotes s for POSIX sh.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// launcherScript is the sh wrapper every launch path (panel, menu,
// keybinding, API) goes through. The marker variable lets Relay tell
// which catalog apps are running on this display.
func launcherScript(a deskApp) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n# Generated by Relay.\n")
	b.WriteString("RELAY_DESKTOP_APP=" + shellQuote(a.ID) + "\nexport RELAY_DESKTOP_APP\n")
	b.WriteString("exec")
	for _, arg := range a.Argv {
		b.WriteString(" " + shellQuote(arg))
	}
	b.WriteString(" \"$@\"\n")
	return b.String()
}

// runningScanner reports which catalog apps have a live process on the
// display, by the RELAY_DESKTOP_APP marker in their environment. Only the
// current user's processes are readable, which is exactly the scope.
type runningScanner struct {
	procDir string
	display string
	ttl     time.Duration

	at   time.Time
	last map[string]bool
}

// Running returns the set of app ids with a live process (cached for ttl).
func (r *runningScanner) Running(now time.Time) map[string]bool {
	if r.last != nil && now.Sub(r.at) < r.ttl {
		return r.last
	}
	r.at, r.last = now, r.scan()
	return r.last
}

// Reset drops the cache (after a launch or when the desktop stops).
func (r *runningScanner) Reset() { r.last = nil }

func (r *runningScanner) scan() map[string]bool {
	out := map[string]bool{}
	ents, err := os.ReadDir(r.procDir)
	if err != nil {
		return out
	}
	uid := os.Getuid()
	wantDisplay := []byte("DISPLAY=" + r.display)
	marker := []byte("RELAY_DESKTOP_APP=")
	for _, e := range ents {
		if _, err := strconv.Atoi(e.Name()); err != nil {
			continue
		}
		dir := filepath.Join(r.procDir, e.Name())
		if !ownedBy(dir, uid) {
			continue
		}
		env, err := os.ReadFile(filepath.Join(dir, "environ"))
		if err != nil || !bytes.Contains(env, marker) {
			continue
		}
		var id string
		display := false
		for _, kv := range bytes.Split(env, []byte{0}) {
			switch {
			case bytes.Equal(kv, wantDisplay):
				display = true
			case bytes.HasPrefix(kv, marker):
				id = string(kv[len(marker):])
			}
		}
		if display && id != "" {
			out[id] = true
		}
	}
	return out
}

// ownedBy reports whether path belongs to uid.
func ownedBy(path string, uid int) bool {
	fi, err := os.Stat(path)
	if err != nil {
		return false
	}
	st, ok := fi.Sys().(*syscall.Stat_t)
	return ok && int(st.Uid) == uid
}
